# This file was generated by GoReleaser. DO NOT EDIT.
class Flyctl < Formula
  desc ""
  homepage "https://fly.io"
  version "0.0.110"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/superfly/flyctl/releases/download/v0.0.110/flyctl_0.0.110_macOS_x86_64.tar.gz"
    sha256 "9171c5faa0eb42babfbf923795a9d33f86c17ede7471f5475241ab8afe1ec9a7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/superfly/flyctl/releases/download/v0.0.110/flyctl_0.0.110_Linux_x86_64.tar.gz"
      sha256 "8e0df078ee0e1327339eb263b6ebfd5ea471bdb3e42f339ed78adbd58f7702df"
    end
  end

  def install
    bin.install "flyctl"
  end

  test do
    system "#{bin}/flyctl version"
  end
end
